### PR TITLE
[UNTESTED] Add a goma client prebuilt

### PR DESCRIPTION
**Pull request by Lambourl**

### CODE REVIEW

**Comment by daminetreg** [comment]
Thanks where does the client come from ?

**Comment by Lambourl** [comment]
the client come from this website : https://chrome-infra-packages.appspot.com/p/infra/goma/client
and I store it in our FTP

**Review by daminetreg — CHANGES_REQUESTED** [review]
- [ ] On linux it does provide a  goma_ctl.py is available but no goma_ctl launcher is available, I think it's true for all .py part.

**Review by daminetreg — CHANGES_REQUESTED** [review]
- [ ] compiler_proxy is in there but not used by the distro, it take the one from depot_tools cipd package instead when available

**Pull request closed without merging**
